name: Build and deploy Node.js app to Azure Web App - frontend-ai-app-d

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build
        run: |
          npm install
          npm run build --if-present

      - name: Clean environment and reinstall dependencies
        run: |
          rm -rf node_modules
          npm ci

      - name: Zip artifact for deployment
        run: |
          zip release.zip ./build/* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip

      - name: Load environment variables from Azure
        uses: Azure/appservice-settings@v1
        with:
          app-name: 'frontend-ai-app-d'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E4E33FA3C68844B19731B4C527D34B26 }}
          action: 'upload'
          settings: '{
            "appSettings": [
              { "name": "REACT_APP_API_URL", "value": "${{ secrets.REACT_APP_API_URL }}" },
              { "name": "REACT_APP_API_KEY", "value": "${{ secrets.REACT_APP_API_KEY }}" },
              { "name": "REACT_APP_AUTH0_DOMAIN", "value": "${{ secrets.REACT_APP_AUTH0_DOMAIN }}" },
              { "name": "REACT_APP_AUTH0_CLIENTID", "value": "${{ secrets.REACT_APP_AUTH0_CLIENTID }}" }
            ]
          }'

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'frontend-ai-app-d'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E4E33FA3C68844B19731B4C527D34B26 }}
          package: .
